serial_port : "/dev/roboteq" # Udev rule to make a virtual port that's associated to specific hw
baudrate : 115200
cmd_vel_topic: "cmd_vel_roboteq"

#i changed this
closed_loop: false

# For differential drive control (dual channel controller)
diff_drive_mode: false
wheel_circumference: 0.398 # [m]
track_width: .254 # [m]
max_rpm: 122 # [rpm]
encoder_resolution: 784

#For odometry
base_frame: "base_link"
odom_frame: "odom"
encoder_topic_name: "/encoder_count"
command_srv: "/dualchannel_command_service"
gear_ratio: 24.69
radius: 0.105
wheelbase: 1.0
rate: 5
ppr: 1024
encoder_max: 65536
encoder_min: -65536

# For querying data from the motor controller
frequency: 100   #higher frequency (value is in ms)
query:
  motor_amps : ?A 
  motor_command : ?M
  # hall_count : ?Cb
  # hall_speed : ?BS
  volts : ?V
  feedback : ?F 
  # battery_amps : ?BA
  # power : ?P          
  # fault_flag : ?FF  
  # motor_amps2 : ?MA
  # motor_command2 : ?FM
  # hall_count2 : ?FM
  # hall_speed2 : ?FS
  # volts2 : ?V
  # feedback2 : ?rmp 
  # battery_amps2 : ?PHA
  # power2 : ?sns          
  # fault_flag2 : ?S  
  # status_flag : ?FS
  # firmware_id : ?FID  
  encoder_count : ?C
  encoder_speed : ?S  
