serial_port : "/dev/ttyACM2" # Udev rule to make a virtual port that's associated to specific hw
baudrate : 115200
cmd_vel_topic: "cmd_vel_roboteq"

closed_loop: true

# # For differential drive control (dual channel controller)
# diff_drive_mode: true
# wheel_circumference: 0.6594 # [m]
# track_width: .6223 # [m]
# max_rpm: 100 # [rpm]
# encoder_resolution: 1024

# For querying data from the motor controller
frequency: 10   #higher frequency (value is in ms)
query:
  encoder_count : ?C
  encoder_speed : ?S  
  motor_voltage : ?V  
